# Site settings
title: Anthony Super
description: > # this means to ignore newlines until "baseurl:"
  Programming thoughts from Anthony Super
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://anthony.noided.media" # the base hostname & protocol for your site
twitter_username: anthonysuper1
github_username:  anthonysuper

#Build settings
markdown: kramdown

kramdown:
  input: GFM 
  hard_wrap: false

highlighter: rouge

excerpt_separator: "<!--more-->"
