# Site settings
title: Anthony Super
description: > # this means to ignore newlines until "baseurl:"
  Personal Blog of Anthony Super, CEO of Noided Media. 
  Includes articles on startups, programming, life, humor, and music.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://anthony.noided.media" # the base hostname & protocol for your site
twitter_username: anthonysuper1
github_username:  anthonysuper
exclude: [node_modules, package.json, yarn.lock]

#Build settings
markdown: kramdown

kramdown:
  input: GFM 
  hard_wrap: false

gems:
  - jekyll-paginate

highlighter: rouge

paginate: 5

paginate_path: "/blog/page:num/"

excerpt_separator: "<!--more-->"
